kind: Deployment
apiVersion: apps/v1
metadata:
  name: archimail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archimail
  template:
    metadata:
      labels:
        app: archimail
    spec:
      containers:
        - name: archimail
          image: localhost:32000/archimail/1.0:latest
          ports:
            - containerPort: 31007
---
apiVersion: v1
kind: Service
metadata:
  name: archimail
  labels:
    app: archimail
spec:
  type: LoadBalancer
  ports:
    - port: 31007
      targetPort: 3333
      protocol: TCP
      nodePort: 31007
  selector:
    app: archimail
